import Input_Password from "../component/Input_Password";
import Appointments from "./Appointments";
import DashBoard from "./DashBoard";
import Doctor from "./Doctor";
import Doctors from "./Doctors";
import Error404 from "./Error404";
import Floor from "./Floor";
import Floors from "./Floors";
import Generics from "./Generics";
import Home from "./Home";
import Invoice from "./Invoice";
import Invoices from "./Invoices";
import Layout from "./Layout";
import Login from "./Login";
import Medicines from "./Medicines";
import NewPatient from "./NewPatient";
import Patient from "./Patient";
import Patients from "./Patients";
import Payment from "./Payment";
import Payments from "./Payments";
import Settings from "./Settings";
import Users from "./Users";

export { Generics,Appointments, DashBoard, Doctor, Doctors, Error404, Floor, Floors, Home, Input_Password, Invoice, Invoices, Layout, Login, Medicines, NewPatient, Patient, Patients, Payment, Payments, Settings, Users };